#!/bin/bash

# Insert here your username and password
USERNAME=""
PASSWORD=""

login_citywifi() {
    # wificity authentication server
    authserver="http://10.254.0.254:1000"

    # 204 http status code generation url to detect captive portal
    # can be any http address, eg. http://neverssl.com
    # but change the "$status" != "204" with correct status code
    # ref. https://github.com/NickSto/uptest/blob/master/captive-portals.md
    gen204="http://detectportal.firefox.com/canonical.html"

    # wificity username password
    username=$1
    password=$2

    # grabbing http response to detect captive portal
    gen204_resp=$(curl -si "$gen204")

    # parsing http status code
    status=$(sed -n '1s/^[^\s]\+ \([0-9]\+\)\(\s.*\)\?$/\1/p' <<< "$gen204_resp")

    # if http status code is not expected
    if [ "$status" != "204" ]; then
        # captive portal is detected
        # assuming wificity network
        # parsing magic code to generate the wificity authentication form
        magic=$(sed -n 's/^Location.*?\([a-zA-Z0-9]\+\).*$/\1/p' <<< "$gen204_resp")
        # generate the authentication form
        curl -so /dev/null "${authserver}/fgtauth?${magic}"
        # submit credentials with magic code to wificity server for authentication
        curl -so /dev/null "$authserver" --data "magic=${magic}&username=${username}&password=${password}"
    fi
}

# NetworkManager passes interface and status as arguments to the dispatch scripts
interface=$1
status=$2

# test if the connection ID is right, and do this only when the interface has been activated
if test "$CONNECTION_ID" = "WifiCity" && test "$status" = "up"; then
	login_citywifi $USERNAME $PASSWORD
	# Optionally insert here the commands to activate a vpn to hide your traffic from CityWifi
    # Eg. wg-quick up wireguard-interface
fi
